@PlanetEvaluateApi_HostAddress = http://localhost:5219

# PlanetEvaluate API Test File
# Use this file to test various endpoints of the Planet Evaluate API
# The WeatherForecast endpoint has been removed as part of cleanup

###
